version: 0.2
  phases:
    install:
      runtime-versions:emphasized text
      java: corretto11
      commands:
        - echo install
    pre_build:
      commands:
        - echo pre_build
    build:
      commands:
        - mvn clean package
        - echo build
    post_build:
      commands:
        - echo post_build
        - mv target/*.jar app.jar

  artifacts:
    files:
      - app.jar